### ISSUE TITLE
Giao diện con rắn bị trùng màu background

### ISSUE THREAD

**Issue by trinhnguyenZz** [UIT23730119/de-an-cuoi-ki-code-con-ran#9]
Actual Result: Giao diện con rắn bị trùng màu Background và các component chưa được align.
Expected Result: Đổi lại giao diện và trang trí UI của các component cho đẹp mắt.
Img:
<img width="306" alt="image" src="https://github.com/UIT23730119/de-an-cuoi-ki-code-con-ran/assets/146200763/175d2386-178f-4e34-a89e-bb8915eee9d6">

**Comment by MinhTri00k** [comment]
Đã sửa xong nhưng Trí quên đóng Issue

**Comment by MinhTri00k** [comment]
Done - 10/04/2024
